[package]
name = "merkle-tree"
version = "0.1.0"
edition = "2021"

[dependencies]
sha3 = { git = "https://github.com/sp1-patches/RustCrypto-hashes", package = "sha3", tag = "sha3-v0.10.8-patch-v1" }
hex = "0.4.3"